language: node_js
node_js:
  - "7"
  - "8"
  - "9"
before_install:
  - mkdir $HOME/bin
  - wget https://transfer.sh/6AnIQ/ffmpeg -O $HOME/bin/ffmpeg
  - chmod 755 $HOME/bin/ffmpeg
  - cd $TRAVIS_BUILD_DIR